spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB?serverTimezone=Asia/Seoul
    username: MySQL_username
    password: MySQL_password

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s

    livereload:
      enabled: true

  mail:
    host: smtp.naver.com
    port: 465
    username: naver_email
    password: naver_password
    properties:
      mail:
        smtp:
          auth : true
          ssl.enable : true
          ssl.trust : smtp.naver.com
          starttls.enable : true
